Gallery2: SLIM Materialization v1
- SLIM Material theme
- FAB
- Add missing resources for movie settings
- Fix action mode
- Vector drawables
- Settings Up Caret Navigation
- New themes for Settings, Crop, Editor

Change-Id: I9c8cc81759502a417a5585fd1d3fd9b61e0bd68b

Gallery2: Fix filtershow renderscript for lollipop

* Use the non support version

Change-Id: Idce8f3f4741def8dcd080f226cd9a0ef909f7eb1

Gallery2: Add clean step after recent changes

out/target/common/obj/APPS/Gallery2_intermediates/src/renderscript
/src/com/android/gallery3d/filtershow/filters/ScriptC_convolve3x3.java:24:
error: package android.support.v8.renderscript does not exist

Change-Id: I8411ec214607d0875bea5e41d93b416585e15592